version: 2.1

jobs:
  my-awesome-hugging-face-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "super-awesome/circleci.yml"
          command: "echo very cool"

workflows:
  super-awesome:
    jobs:
      - my-awesome-hugging-face-job